### PR TITLE
Phoenix.LiveDashboard support

### LINKED ISSUE #1: Would you be interested in supporting phoenix_live_dashboard?
Hi @pawurb! Thanks for the extremely useful repo!

Over the last weeks @alexcastano has been working on custom pages for the [Phoenix Live Dashboard](https://github.com/phoenixframework/phoenix_live_dashboard). Our main goal is to support something like `ecto_psql_extras`, but directly from the browser.

Now that the foundational work is done, we are discussing where to integrate the functionality. One approach that came to mind is to add the functionality directly here. Would you be interested in adding support for the Phoenix Live Dashboard in `ecto_psql_extras`? `phoenix_live_dashboard` would become an optional dependency. The amount of work necessary is also minimal, you can see [the page itself here](https://github.com/phoenixframework/phoenix_live_dashboard/pull/191/files#diff-c29dfb3c33ce083ab9c622f9a083c89d) - where the name of columns could probably be defined alongside each query in this repo and the all possible queries could also be made public.

Please let us know what you think, we will be glad to submit a PR! :)

### PR DESCRIPTION
**Pull request by alexcastano**
Closes #1 

Unfortunately, I couldn't make it work in a similar way the command `mix dev` works in LiveDashboard repository. The Phoenix doesn't start and I don't know why.

I added some deps the project needs to work correctly like `postgrex` & `ecto_sql`, but not 100% sure about this.

It is still a work in progress. It would be interesting to add some tests, a little bit of introspection to know the columns of each query to make easier the page, etc.

### CODE REVIEW

**Comment by pawurb** [comment]
@alexcastano looking at the amount of changes needed I'm having second thoughts about adding it directly to this project.

I have Ruby/Rails implementation of this library, https://github.com/pawurb/rails-pg-extras and https://github.com/pawurb/ruby-pg-extras . Ruby version includes the core functionality like this package, and only Rails version implements framework specific code.

Maybe you could follow the same path here? You could add a new package and only include ecto_psql_extras as a dependency? It will also be easier for you to work in your own repo. I'm still open to making some API changes if necessary.

**Comment by alexcastano** [comment]
No worries!! It's your package and your call :)

Let me explain at least the changes:

The dependencies that aren't optional I think they are needed anyway for the package AFAIK. For example, if you tried to create a test it would fail because the packages to connect to the database are missing.

The dashboard.exs file is only for development. It's used to launch a Phoenix so we can test the dashboard page easily. The dev dependencies are needed for launching this file.

The optional dep shouldn't affect to the current users. The psql_stats_page.ex is only compiled if the user also installed the dashboard. I think this file could be much smaller if we could know the columns of each query. It would be reduced to only a 20% of the current size.

Anyway, as you already proposed, we can create a new package which uses this one to create the dashboard package. I just wanted to explain the code a little before you taking the final decision. Feel free to close the PR, no worries.

Thank you for your package and your time.

PD: I won't be able to finish this project in the following weeks. I have got an unexpected situation :)

**Comment by pawurb** [comment]
@alexcastano I'd rather follow the convention of Ruby/Rails PG extras packages. So I'll close it for now and let me know if some changes in the core dependency will be needed.

**Comment by josevalim** [comment]
I would like to propose two changes from this PR though:

1. Can each query module define all of the columns they return? This will make our lives much easier and reduce coupling

2. Can you have a function that returns all query modules? This way if we add new queries to this repo, they automatically work.

Basically, the idea is to make the API here a bit more reflective. If we do so, the LiveView itself will be like 30LOC and then we can even add them to the LiveDashboard itself!

What do you think?

**Comment by pawurb** [comment]
@josevalim @alexcastano sure these changes sound ok. If we can the make this package API more useful without adding additional dependencies I'd accept it.

**Comment by josevalim** [comment]
@pawurb I sent a PR here: https://github.com/pawurb/ecto_psql_extras/pull/3 - The queries are the same, we just have more metadata about them. :)

@alexcastano, I assume with the PR above we should be able to generate the dashboard page automatically. If that's the case, I would just make it part of `phoenix_live_dashboard`. We can keep the page disabled by default until users install `ecto_psql_extras`. :)

**Pull request closed without merging**
