### PR TITLE
Fix Elixir 1.15 warning, require Elixir 1.11+ & bump Ecto/Postgrex requirements

### PR DESCRIPTION
**Pull request by thbar**
This PR addresses multiple maintenance points.

### Move to Elixir 1.11+ & fix Elixir 1.15 warning

As seen in other places:
- https://github.com/elixir-ecto/ecto/pull/4212/files
- https://github.com/sneako/finch/pull/232/files

There is a trend to move to Elixir 1.11+ (oldest maintained version) all while removing the `Logger.warn` in favour of `Logger.warning`. 

This PR addresses that.

### Bump Ecto/Postgrex minimal versions & fix CI

The PR also addresses:
- #47 

since the CI system was broken.

As described in https://brianmeeker.me/2023/05/24/otp-26-ecto-dynamic-error/, Ecto had to be bumped in the "lock" file at least for OTP 26, but to be able get there on CI I ended up bumping `mix.exs` versions (rather than the lock file) for Ecto & Postgrex. I believe this is acceptable since previous constraints were on oldish versions.

### CODE REVIEW

**Comment by pawurb** [comment]
@thbar thanks for a PR! I think that CI currently does not work because of legacy Ubuntu version that you've mentioned. I'm looking forward to merge this PR, but can you try to fix CI before we merge it?

**Comment by thbar** [comment]
@pawurb I will look into CI fixes in the same PR to keep things simple! Will keep you posted.

**Comment by thbar** [comment]
@pawurb I've fixed the CI (at the cost of bumping some requirements), but I believe you'll have to fix the settings to remove some jobs from the expected statuses.

Other than that, the tests pass.

**Comment by pawurb** [comment]
@thbar thanks! It's now released as 0.7.12

**Pull request merged**
